# Generated by Django 3.2.8 on 2021-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0002_auto_20211019_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(choices=[('1', 'sports'), ('2', 'all')], default='All', max_length=30),
        ),
    ]
