# Generated by Django 3.2.8 on 2021-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0003_newsarticle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(choices=[(0, 'News'), (1, 'Local'), (2, 'Sprots'), (3, 'Children'), (4, 'Life'), (5, 'Tech'), (6, 'Astro'), (7, 'Health'), (8, 'Movie'), (9, 'Carrer'), (10, 'Travel')], default='1', max_length=30),
        ),
    ]
