# Generated by Django 3.2.8 on 2021-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0005_alter_newsarticle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
