# Generated by Django 3.2.8 on 2021-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0008_alter_newsarticle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='desc',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='pic_url',
            field=models.URLField(default=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='pic',
            field=models.ImageField(default='IMG', null=True, upload_to='images/'),
        ),
    ]
