# Generated by Django 3.2.8 on 2021-10-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0009_auto_20211021_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='newsArticle',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='News_App.comment'),
            preserve_default=False,
        ),
    ]
