# Generated by Django 3.2.8 on 2021-10-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0011_auto_20211021_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('newsArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='News_App.newsarticle')),
            ],
        ),
    ]
