# Generated by Django 3.2.8 on 2021-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0013_auto_20211021_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
