# Generated by Django 3.2.8 on 2021-10-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0014_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
