# Generated by Django 3.2.8 on 2021-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0016_auto_20211022_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(choices=[('Top News', 'Top News'), ('Trending', 'Trending'), ('News', 'News'), ('Sports', 'Sports'), ('Health', 'Health'), ('Children', 'Children'), ('Life', 'Life'), ('Tech', 'Tech'), ('Astro', 'Astro'), ('Health', 'Health'), ('Movie', 'Movie'), ('Carrer', 'Carrer'), ('Travel', 'Travel'), ('Home', 'Home'), ('Auto', 'Auto'), ('Music', 'Music')], default='News', max_length=30),
        ),
    ]
